using System;
using System.Collections.Generic;
using UnityEngine;

namespace GameLabs.Forge
{
    /// <summary>
    /// Registry for item types that can be generated by Forge.
    /// Allows runtime registration of custom item types.
    /// </summary>
    public static class ForgeTypeRegistry
    {
        private static readonly Dictionary<string, Type> _registeredTypes = new Dictionary<string, Type>();
        private static readonly Dictionary<Type, ForgeSchemaExtractor.TypeSchema> _schemaCache = new Dictionary<Type, ForgeSchemaExtractor.TypeSchema>();
        
        /// <summary>
        /// Registers an item type with Forge.
        /// </summary>
        public static void RegisterType<T>(string customName = null) where T : class
        {
            var type = typeof(T);
            var name = customName ?? type.Name;
            
            if (_registeredTypes.ContainsKey(name))
            {
                ForgeLogger.Warn($"Type '{name}' is already registered. Overwriting.");
            }
            
            _registeredTypes[name] = type;
            _schemaCache[type] = ForgeSchemaExtractor.ExtractSchema<T>();
            
            ForgeLogger.DebugLog($"Registered type: {name}");
        }
        
        /// <summary>
        /// Gets a registered type by name.
        /// </summary>
        public static Type GetType(string name)
        {
            return _registeredTypes.TryGetValue(name, out var type) ? type : null;
        }
        
        /// <summary>
        /// Gets the cached schema for a type.
        /// </summary>
        public static ForgeSchemaExtractor.TypeSchema GetSchema(Type type)
        {
            if (_schemaCache.TryGetValue(type, out var schema))
                return schema;
            
            schema = ForgeSchemaExtractor.ExtractSchema(type);
            _schemaCache[type] = schema;
            return schema;
        }
        
        /// <summary>
        /// Gets the cached schema for a type.
        /// </summary>
        public static ForgeSchemaExtractor.TypeSchema GetSchema<T>() where T : class
        {
            return GetSchema(typeof(T));
        }
        
        /// <summary>
        /// Gets all registered type names.
        /// </summary>
        public static IEnumerable<string> GetRegisteredTypeNames()
        {
            return _registeredTypes.Keys;
        }
        
        /// <summary>
        /// Checks if a type is registered.
        /// </summary>
        public static bool IsRegistered(string name)
        {
            return _registeredTypes.ContainsKey(name);
        }
        
        /// <summary>
        /// Clears all registered types.
        /// </summary>
        public static void ClearRegistry()
        {
            _registeredTypes.Clear();
            _schemaCache.Clear();
        }
        
        /// <summary>
        /// Automatically registers all types that inherit from ForgeItemDefinition
        /// in the current assembly.
        /// </summary>
        public static void AutoRegisterItemDefinitions()
        {
            var baseType = typeof(ForgeItemDefinition);
            
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                try
                {
                    foreach (var type in assembly.GetTypes())
                    {
                        if (type.IsClass && !type.IsAbstract && baseType.IsAssignableFrom(type))
                        {
                            if (!_registeredTypes.ContainsValue(type))
                            {
                                _registeredTypes[type.Name] = type;
                                _schemaCache[type] = ForgeSchemaExtractor.ExtractSchema(type);
                            }
                        }
                    }
                }
                catch (Exception e)
                {
                    // Skip assemblies that can't be inspected - this is expected for some system assemblies
                    ForgeLogger.DebugLog($"Skipped assembly during auto-registration: {assembly.FullName} ({e.GetType().Name})");
                }
            }
            
            ForgeLogger.DebugLog($"Auto-registered {_registeredTypes.Count} item types.");
        }
    }
}
