using System;
using UnityEngine;

namespace GameLabs.Forge
{
    /// <summary>
    /// Base class for typed ScriptableObject assets that can be automatically
    /// populated from generated ForgeItemDefinition data.
    /// 
    /// Inherit from this class to create typed game items that can be:
    /// - Generated by AI and saved directly as usable ScriptableObjects
    /// - Referenced in the Unity Inspector
    /// - Used immediately in your game without any conversion
    /// 
    /// <example>
    /// <code>
    /// [CreateAssetMenu(fileName = "New Weapon", menuName = "Game/Items/Melee Weapon")]
    /// public class MeleeWeaponAsset : ForgeTypedAsset
    /// {
    ///     [Header("Combat Stats")]
    ///     public int damage;
    ///     public float attackSpeed;
    ///     
    ///     [Header("Item Properties")]
    ///     public float weight;
    ///     public int value;
    ///     public ItemRarity rarity;
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public abstract class ForgeTypedAsset : ScriptableObject
    {
        /// <summary>Unique identifier for this item.</summary>
        [Header("Base Info")]
        [Tooltip("Unique identifier for this item")]
        public string id;
        
        /// <summary>Display name of the item.</summary>
        [Tooltip("Display name of the item")]
        public new string name;
        
        /// <summary>Description of the item.</summary>
        [Tooltip("Description of the item")]
        [TextArea(2, 4)]
        public string description;
        
        /// <summary>The type name of the source ForgeItemDefinition used to generate this asset.</summary>
        [HideInInspector]
        [SerializeField] private string _sourceTypeName;
        
        /// <summary>Timestamp when this asset was generated.</summary>
        [HideInInspector]
        [SerializeField] private string _generatedAt;
        
        /// <summary>The raw JSON data used to populate this asset (for debugging/reference).</summary>
        [HideInInspector]
        [SerializeField] private string _sourceJson;
        
        /// <summary>Gets the source type name that was used to generate this asset.</summary>
        public string SourceTypeName => _sourceTypeName;
        
        /// <summary>Gets when this asset was generated.</summary>
        public DateTime GeneratedAt => DateTime.TryParse(_generatedAt, out var dt) ? dt : DateTime.MinValue;
        
        /// <summary>Gets the raw source JSON data.</summary>
        public string SourceJson => _sourceJson;
        
        /// <summary>
        /// Called internally when the asset is populated from generated data.
        /// Override to add custom post-processing logic.
        /// </summary>
        /// <param name="sourceTypeName">The name of the source ForgeItemDefinition type.</param>
        /// <param name="sourceJson">The raw JSON data that was used.</param>
        public virtual void OnPopulated(string sourceTypeName, string sourceJson)
        {
            _sourceTypeName = sourceTypeName;
            _sourceJson = sourceJson;
            _generatedAt = DateTime.Now.ToString("o");
        }
        
        /// <summary>
        /// Called after all fields have been populated. Override to add validation
        /// or post-processing logic (e.g., calculating derived values, clamping stats).
        /// </summary>
        public virtual void OnValidateGenerated()
        {
            // Ensure we have an ID
            if (string.IsNullOrEmpty(id))
            {
                id = Guid.NewGuid().ToString("N").Substring(0, 8);
            }
        }
        
        /// <summary>
        /// Gets a display name for this asset suitable for the Unity Inspector.
        /// </summary>
        public virtual string GetDisplayName()
        {
            return !string.IsNullOrEmpty(name) ? name : base.name;
        }
    }
}
