using UnityEngine;
using GameLabs.Forge;

/// <summary>
/// Typed ScriptableObject asset for Armor items.
/// This asset can be generated by Forge and used directly in your game
/// with real Inspector properties - no JSON parsing required!
/// </summary>
[CreateAssetMenu(fileName = "New Armor", menuName = "GameLabs/Forge/Items/Armor")]
public class ArmorAsset : ForgeTypedAsset
{
    [Header("Defense Stats")]
    [Tooltip("Equipment slot")]
    public ArmorSlot slot;
    
    [Tooltip("Defense rating")]
    [Range(1, 200)]
    public int defense = 10;
    
    [Tooltip("Bonus health from wearing")]
    [Range(0, 100)]
    public int bonusHealth = 0;
    
    [Header("Physical Properties")]
    [Tooltip("Weight in kg")]
    [Range(0.1f, 100f)]
    public float weight = 5.0f;
    
    [Tooltip("Movement speed modifier (1.0 = normal)")]
    [Range(0.5f, 1.5f)]
    public float speedModifier = 1.0f;
    
    [Header("Item Properties")]
    [Tooltip("Gold value")]
    [Range(1, 10000)]
    public int value = 100;
    
    [Tooltip("Durability")]
    [Range(1, 1000)]
    public int durability = 100;
    
    [Tooltip("Armor type/material")]
    public ArmorType armorType;
    
    [Tooltip("Rarity tier")]
    public ItemRarity rarity;
    
    /// <summary>
    /// Gets the effective defense considering speed penalty tradeoff.
    /// </summary>
    public float GetEffectiveDefense()
    {
        // Higher speed modifier = lower penalty, so better effective defense
        return defense * speedModifier;
    }
    
    /// <summary>
    /// Gets the total defensive value (defense + bonus health contribution).
    /// </summary>
    public float GetTotalDefensiveValue()
    {
        return defense + (bonusHealth * 0.5f);
    }
    
    /// <summary>
    /// Called after all fields are populated from generated data.
    /// </summary>
    public override void OnValidateGenerated()
    {
        base.OnValidateGenerated();
        
        // Clamp values to valid ranges
        defense = Mathf.Clamp(defense, 1, 200);
        bonusHealth = Mathf.Clamp(bonusHealth, 0, 100);
        weight = Mathf.Clamp(weight, 0.1f, 100f);
        speedModifier = Mathf.Clamp(speedModifier, 0.5f, 1.5f);
        value = Mathf.Clamp(value, 1, 10000);
        durability = Mathf.Clamp(durability, 1, 1000);
    }
}
