using UnityEngine;
using GameLabs.Forge;

/// <summary>
/// Typed ScriptableObject asset for Collectible items.
/// This asset can be generated by Forge and used directly in your game
/// with real Inspector properties - no JSON parsing required!
/// </summary>
[CreateAssetMenu(fileName = "New Collectible", menuName = "GameLabs/Forge/Items/Collectible")]
public class CollectibleAsset : ForgeTypedAsset
{
    [Header("Collectible Type")]
    [Tooltip("Category of collectible")]
    public CollectibleCategory category;
    
    [Tooltip("Is this item unique (only one can exist)?")]
    public bool isUnique = false;
    
    [Tooltip("Set name if part of a collection")]
    public string setName = "";
    
    [Header("Item Properties")]
    [Tooltip("Gold value")]
    [Range(1, 50000)]
    public int value = 100;
    
    [Tooltip("Rarity tier")]
    public ItemRarity rarity;
    
    [Header("Lore")]
    [Tooltip("Lore/backstory of the item")]
    [TextArea(2, 4)]
    public string lore = "";
    
    /// <summary>
    /// Checks if this collectible belongs to a set.
    /// </summary>
    public bool IsPartOfSet => !string.IsNullOrEmpty(setName);
    
    /// <summary>
    /// Gets the base value adjusted for rarity.
    /// </summary>
    public int GetRarityAdjustedValue()
    {
        float multiplier = rarity switch
        {
            ItemRarity.Common => 1.0f,
            ItemRarity.Uncommon => 1.5f,
            ItemRarity.Rare => 2.5f,
            ItemRarity.Epic => 5.0f,
            ItemRarity.Legendary => 10.0f,
            _ => 1.0f
        };
        return Mathf.RoundToInt(value * multiplier);
    }
    
    /// <summary>
    /// Called after all fields are populated from generated data.
    /// </summary>
    public override void OnValidateGenerated()
    {
        base.OnValidateGenerated();
        
        // Clamp values to valid ranges
        value = Mathf.Clamp(value, 1, 50000);
    }
}
