using UnityEngine;
using GameLabs.Forge;

/// <summary>
/// Typed ScriptableObject asset for Consumable items.
/// This asset can be generated by Forge and used directly in your game
/// with real Inspector properties - no JSON parsing required!
/// </summary>
[CreateAssetMenu(fileName = "New Consumable", menuName = "GameLabs/Forge/Items/Consumable")]
public class ConsumableAsset : ForgeTypedAsset
{
    [Header("Effect")]
    [Tooltip("Effect type when consumed")]
    public ConsumableEffect effectType;
    
    [Tooltip("Power/magnitude of the effect")]
    [Range(1, 100)]
    public int effectPower = 10;
    
    [Tooltip("Duration of effect in seconds (0 for instant)")]
    [Range(0, 300)]
    public float duration = 0;
    
    [Header("Item Properties")]
    [Tooltip("Gold value")]
    [Range(1, 1000)]
    public int value = 25;
    
    [Tooltip("Maximum stack size")]
    [Range(1, 99)]
    public int maxStack = 20;
    
    [Tooltip("Rarity tier")]
    public ItemRarity rarity;
    
    /// <summary>
    /// Gets whether this consumable has an instant or duration-based effect.
    /// </summary>
    public bool IsInstant => duration <= 0;
    
    /// <summary>
    /// Calculates the effect power per second for duration-based effects.
    /// </summary>
    public float GetEffectPerSecond()
    {
        return duration > 0 ? effectPower / duration : effectPower;
    }
    
    /// <summary>
    /// Called after all fields are populated from generated data.
    /// </summary>
    public override void OnValidateGenerated()
    {
        base.OnValidateGenerated();
        
        // Clamp values to valid ranges
        effectPower = Mathf.Clamp(effectPower, 1, 100);
        duration = Mathf.Clamp(duration, 0, 300);
        value = Mathf.Clamp(value, 1, 1000);
        maxStack = Mathf.Clamp(maxStack, 1, 99);
    }
}
