using UnityEngine;
using GameLabs.Forge;

/// <summary>
/// Typed ScriptableObject asset for MeleeWeapon items.
/// This asset can be generated by Forge and used directly in your game
/// with real Inspector properties - no JSON parsing required!
/// 
/// Usage:
/// 1. Generate MeleeWeapon items using the Forge Generator
/// 2. The [ForgeAssetBinding] attribute on MeleeWeapon ensures
///    typed assets are created automatically
/// 3. Reference these assets directly in your game scripts/prefabs
/// </summary>
[CreateAssetMenu(fileName = "New Melee Weapon", menuName = "GameLabs/Forge/Items/Melee Weapon")]
public class MeleeWeaponAsset : ForgeTypedAsset
{
    [Header("Combat Stats")]
    [Tooltip("Base damage dealt by the weapon")]
    [Range(1, 100)]
    public int damage = 10;
    
    [Tooltip("Attack speed (attacks per second)")]
    [Range(0.5f, 5f)]
    public float attackSpeed = 1.0f;
    
    [Tooltip("Durability of the weapon")]
    [Range(1, 500)]
    public int durability = 100;
    
    [Header("Physical Properties")]
    [Tooltip("Weight of the weapon in kg")]
    [Range(0.1f, 50f)]
    public float weight = 1.0f;
    
    [Header("Item Properties")]
    [Tooltip("Gold value of the weapon")]
    [Range(1, 10000)]
    public int value = 50;
    
    [Tooltip("Type/category of melee weapon")]
    public MeleeWeaponType weaponType;
    
    [Tooltip("Rarity tier of the weapon")]
    public ItemRarity rarity;
    
    /// <summary>
    /// Calculates the DPS (damage per second) of this weapon.
    /// </summary>
    public float CalculateDPS()
    {
        return damage * attackSpeed;
    }
    
    /// <summary>
    /// Gets the value-to-weight ratio (useful for inventory management).
    /// </summary>
    public float GetValuePerWeight()
    {
        return weight > 0 ? value / weight : 0;
    }
    
    /// <summary>
    /// Called after all fields are populated from generated data.
    /// Add any validation or derived calculations here.
    /// </summary>
    public override void OnValidateGenerated()
    {
        base.OnValidateGenerated();
        
        // Clamp values to valid ranges
        damage = Mathf.Clamp(damage, 1, 100);
        attackSpeed = Mathf.Clamp(attackSpeed, 0.5f, 5f);
        durability = Mathf.Clamp(durability, 1, 500);
        weight = Mathf.Clamp(weight, 0.1f, 50f);
        value = Mathf.Clamp(value, 1, 10000);
    }
    
    /// <summary>
    /// Gets a display name suitable for UI.
    /// </summary>
    public override string GetDisplayName()
    {
        if (!string.IsNullOrEmpty(name))
        {
            return $"{name} ({rarity})";
        }
        return base.GetDisplayName();
    }
}
